[tool.black]
line-length = 119
exclude = '''
/(
   \.git
  | \.venv
  | sc2
  | data
)/
'''
[tool.pytest.ini_options]
pythonpath = [
    "ender",
]
[tool.pyright]
pythonVersion= "3.9"
exclude = [
    "sc2"
]
reportUnusedExpression="error"
reportUnusedCoroutine="error"
