name: Code check

on: [pull_request]
jobs:
  build:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dev tools
        run: |
          pip install -r requirements.dev.txt
          pip install -r requirements.txt
      - name: Run black check
        run: |
          black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name 'auto-formatter'
          git config --global user.email 'auto-formatter@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "Fix: Code Format with Black"
          git push
      - name: Run flake8
        run: flake8
      - name: Run pyright
        run: pyright .