name: Zip file
on: [push]
jobs:
  versioning:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
          branch: main
          change_path: "ender"
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"